export const ejercicios = [
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Press de banca con barra",
    imagenEjercicio: "/rutina/filtro2/Press de banca con barra.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Apertura con mancuernas",
    imagenEjercicio: "/rutina/filtro2/Apertura con mancuernas.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Press inclinado con barra",
    imagenEjercicio: "/rutina/filtro2/Press inclinado con barra.png",
    fuerza: { series: 5, repeticiones: 5 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Flexión de arquero",
    imagenEjercicio: "/rutina/filtro2/Flexión de arquero.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Hex press con mancuernas",
    imagenEjercicio: "/rutina/filtro2/Hex press con mancuernas.png",
    fuerza: { series: 4, repeticiones: 5 },
    hipertrofia: { series: 3, repeticiones: 10 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Pull-over con mancuernas",
    imagenEjercicio: "/rutina/filtro2/Pull-over con mancuernas.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "PECHO",
    imagenGrupo: "/rutina/filtro2/pecho.png",
    ejercicio: "Fondos",
    imagenEjercicio: "/rutina/filtro2/fondos.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },

  {
    grupo: "BRAZO",
    imagenGrupo: "/rutina/filtro2/brazo.png",
    ejercicio: "Curl de bíceps con barra olímpica",
    imagenEjercicio: "/rutina/filtro2/Curl de bíceps con barra olímpica.png",
    fuerza: { series: 5, repeticiones: 5 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "BRAZO",
    imagenGrupo: "/rutina/filtro2/brazo.png",
    ejercicio: "Curl concentrado",
    imagenEjercicio: "/rutina/filtro2/Curl concentrado.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "BRAZO",
    imagenGrupo: "/rutina/filtro2/brazo.png",
    ejercicio: "Curl de bíceps con barra Z",
    imagenEjercicio: "/rutina/filtro2/Curl de bíceps con barra Z.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "BRAZO",
    imagenGrupo: "/rutina/filtro2/brazo.png",
    ejercicio: "Curl de bíceps con banda de resistencia",
    imagenEjercicio:
      "/rutina/filtro2/Curl de bíceps con banda de resistencia.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },

  {
    grupo: "TRICEP",
    imagenGrupo: "/rutina/filtro2/tricep.png",
    ejercicio: "Flexiones con manos juntas",
    imagenEjercicio: "/rutina/filtro2/Flexiones con manos juntas.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "TRICEP",
    imagenGrupo: "/rutina/filtro2/tricep.png",
    ejercicio: "Extensiones en TRX",
    imagenEjercicio: "/rutina/filtro2/Extensiones en TRX.png",
    fuerza: { series: 4, repeticiones: 5 },
    hipertrofia: { series: 3, repeticiones: 10 },
  },
  {
    grupo: "TRICEP",
    imagenGrupo: "/rutina/filtro2/tricep.png",
    ejercicio: "Extensiones con mancuerna en banco",
    imagenEjercicio: "/rutina/filtro2/Extensiones con mancuerna en banco.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "TRICEP",
    imagenGrupo: "/rutina/filtro2/tricep.png",
    ejercicio: "Press francés con mancuernas",
    imagenEjercicio: "/rutina/filtro2/Press francés con mancuernas.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },

  {
    grupo: "ESPALDA",
    imagenGrupo: "/rutina/filtro2/espalda.png",
    ejercicio: "Remo con mancuerna a una mano",
    imagenEjercicio: "/rutina/filtro2/Remo con mancuerna a una mano.png",
    fuerza: { series: 5, repeticiones: 5 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },

  {
    grupo: "ESPALDA",
    imagenGrupo: "/rutina/filtro2/espalda.png",
    ejercicio: "Remo con barra",
    imagenEjercicio: "/rutina/filtro2/Remo con barra.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "ESPALDA",
    imagenGrupo: "/rutina/filtro2/espalda.png",
    ejercicio: "LUMBARES",
    imagenEjercicio: "/rutina/filtro2/lumbares.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
  {
    grupo: "ESPALDA",
    imagenGrupo: "/rutina/filtro2/espalda.png",
    ejercicio: "Remo en máquina",
    imagenEjercicio: "/rutina/filtro2/Remo en máquina.png",
    fuerza: { series: 4, repeticiones: 5 },
    hipertrofia: { series: 3, repeticiones: 10 },
  },

  {
    grupo: "PIERNA",
    imagenGrupo: "/rutina/filtro2/pierna.png",
    ejercicio: "Sentadillas con barra",
    imagenEjercicio: "/rutina/filtro2/Sentadillas con barra.png",
    fuerza: { series: 5, repeticiones: 4 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "PIERNA",
    imagenGrupo: "/rutina/filtro2/pierna.png",
    ejercicio: "Sentadilla frontal",
    imagenEjercicio: "/rutina/filtro2/Sentadilla frontal.png",
    fuerza: { series: 5, repeticiones: 5 },
    hipertrofia: { series: 4, repeticiones: 10 },
  },
  {
    grupo: "PIERNA",
    imagenGrupo: "/rutina/filtro2/pierna.png",
    ejercicio: "Peso muerto",
    imagenEjercicio: "/rutina/filtro2/Peso muerto.png",
    fuerza: { series: 5, repeticiones: 3 },
    hipertrofia: { series: 4, repeticiones: 8 },
  },
  {
    grupo: "PIERNA",
    imagenGrupo: "/rutina/filtro2/pierna.png",
    ejercicio: "Sentadilla búlgara",
    imagenEjercicio: "/rutina/filtro2/Sentadilla búlgara.png",
    fuerza: { series: 4, repeticiones: 6 },
    hipertrofia: { series: 3, repeticiones: 12 },
  },
];

export const cardioActivities = [
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Boxeo",
    imagenEjercicio: "/rutina/filtro3/Boxeo.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "FullBody",
    imagenEjercicio: "/rutina/filtro3/FullBody.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Funcional",
    imagenEjercicio: "/rutina/filtro3/Funcional.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "HIIT",
    imagenEjercicio: "/rutina/filtro3/HIIT.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Pilates",
    imagenEjercicio: "/rutina/filtro3/Pilates.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Powerlifting",
    imagenEjercicio: "/rutina/filtro3/Powerlifting.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Spinning",
    imagenEjercicio: "/rutina/filtro3/Spinning.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Clase",
    imagenGrupo: "/rutina/filtro3/Clases.png",
    ejercicio: "Zumba",
    imagenEjercicio: "/rutina/filtro3/Zumba.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Air Bike",
    imagenEjercicio: "/rutina/filtro3/Air Bike.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Bicicleta estática",
    imagenEjercicio: "/rutina/filtro3/Bicicleta estática.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Cinta de correr",
    imagenEjercicio: "/rutina/filtro3/Cinta de correr.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Elíptica",
    imagenEjercicio: "/rutina/filtro3/Elíptica.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Escaladora",
    imagenEjercicio: "/rutina/filtro3/Escaladora.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
  {
    grupo: "Máquina",
    imagenGrupo: "/rutina/filtro3/maquinas.png",
    ejercicio: "Remadora",
    imagenEjercicio: "/rutina/filtro3/Remadora.png",
    resistencia: { series: 1, repeticiones: " 30 min" },
  },
];

export const trainingGoals = [
  "Fuerza máxima",
  "Hipertrofia",
  "Resistencia muscular",
];
