import { Useradmin } from "@/types";

export const allUsers: Useradmin[] = [
  {
    id: "1",
    name: "Carlos Pérez",
    email: "carlos.perez@email.com",
    password: "12345678",
    address: "Calle 123, Bogotá",
    phone: "3001234567",
    type: "user",
    plan: "mensual",
    dateregis: "2024-09-21",
    status: "Activo",
    isBlocked: false,
  },
  {
    id: "2",
    name: "María Gómez",
    email: "maria.gomez@email.com",
    password: "abcdef12",
    address: "Cra 45 #10-25, Medellín",
    phone: "3109876543",
    type: "admin",
    plan: "ninguno",
    dateregis: "2025-01-21",
    status: "Inactivo",
    isBlocked: false,
  },
  {
    id: "3",
    name: "Juan Rodríguez",
    email: "juan.rodriguez@email.com",
    password: "qwerty99",
    address: "Av. Siempre Viva 742, Cali",
    phone: "3154567890",
    type: "user",
    plan: "mensual",
    dateregis: "2025-03-21",
    status: "Activo",
    isBlocked: false,
  },
  {
    id: "4",
    name: "Ana Martínez",
    email: "ana.martinez@email.com",
    password: "password01",
    address: "Transversal 7 #55-20, Barranquilla",
    phone: "3012345678",
    type: "user",
    plan: "anual",
    dateregis: "2025-05-30",
    status: "Activo",
    isBlocked: false,
  },
];
